name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "TextSound Saver"
          keywords: TextToSpeech,Speech,TextSoundSaver,TextSound,Sound
          favicon: https://github.com/jaywcjlove/TextSoundSaver/assets/1680273/4d5d512e-40d2-4cb6-9605-404ead05d8a9.png
          logo: https://github.com/jaywcjlove/TextSoundSaver/assets/1680273/4d5d512e-40d2-4cb6-9605-404ead05d8a9.png
          openSource: https://github.com/jaywcjlove/TextSoundSaver
          tocs: false
          menus:
            Home: index.html
            DevHub: https://jaywcjlove.github.io/DevHub/
          sideEffectFiles:
            - README.zh.md
          EOF

      - run: npm install idoc@1.27.2 -g
      - run: idoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist